name = "gilba"
type = "javascript"
account_id = "c99779f598d17f254bc96f9e7e2f7e88"
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [
    { binding = "SCHEDULE", id = "329cebd1ff774458af5f4cbbab474aea" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
